var swear_en = [ '🖕', 'zoophilia', 'yiffy', 'yellow showers', 'yaoi', 'xxx', 'xx', 'wrinkled starfish', 'wrapping men', 'white power', 
'wet dream', 'wetback', 'wank', 'vulva', 'voyeur', 'vorarephilia', 'violet wand', 'vibrator', 'venus mound', 'vagina', 
'urophilia', 'urethra play', 'upskirt', 'undressing', 'two girls one cup', 'twinkie', 'twink', 'twat', 'tushy', 'tubgirl', 
'tub girl', 'tribadism', 'tranny', 'towelhead', 'tosser', 'topless', 'tongue in a', 'titty', 'titties', 'tits', 
'tit', 'tight white', 'tied up', 'throating', 'threesome', 'tea bagging', 'taste my', 'tainted love', 'swinger', 'swastika', 
'sultry women', 'suicide girls', 'sucks', 'suck', 'style doggy', 'strip club', 'strappado', 'strapon', 'strap on', 'spunk', 
'spread legs', 'spooge', 'splooge moose', 'splooge', 'spic', 'sodomy', 'sodomize', 'snowballing', 'snatch', 'smut', 
's&m', 'slut', 'slanteye', 'skeet', 'shrimping', 'shota', 'shitty', 'shitblimp', 'shit', 'shibari', 
'shemale', 'shaved pussy', 'shaved beaver', 'sexy', 'sexo', 'sex', 'semen', 'scissoring', 'schlong', 'scat', 
'santorum', 'sadism', 'rusty trombone', 'rosy palm and her 5 sisters', 'rosy palm', 'rimming', 'rimjob', 'reverse cowgirl', 'rectum', 'rapist', 
'raping', 'rape', 'raging boner', 'raghead', 'quim', 'queef', 'queaf', 'pussy', 'pubes', 'pthc', 
'prince albert piercing', 'pornography', 'porno', 'porn', 'poopchute', 'poop chute', 'punany', 'poontang', 'poon', 'poof', 
'ponyplay', 'pole smoker', 'pleasure chest', 'playboy', 'pisspig', 'piss pig', 'pissing', 'piece of shit', 'phone sex', 'penis', 
'pegging', 'pedophile', 'pedobear', 'panty', 'panties', 'paki', 'paedophile', 'orgy', 'orgasm', 'one guy one jar', 
'one cup two girls', 'omorashi', 'octopussy', 'nymphomania', 'nympho', 'nudity', 'nude', 'nsfw images', 'nipples', 'nipple', 
'nimphomania', 'nig nog', 'nigger', 'nigga', 'neonazi', 'negro', 'nawashi', 'nambla', 'muffdiving', 'muff diver', 
'mr hands', 'mound of venus', 'motherfucker', 'missionary position', 'milf', 'menage a trois', 'masturbate', 'male squirting', 'make me come', 'lovemaking', 
'lolita', 'lemon party', 'leather straight jacket', 'leather restraint', 'knobbing', 'kinky', 'kinkster', 'kinbaku', 'kike', 'juggs', 
'jizz', 'jiggerboo', 'jiggaboo', 'jigaboo', 'jerk off', 'jelly donut', 'jailbait', 'jail bait', 'jack off', 'intercourse', 
'incest', 'humping', 'huge fat', 'how to murder', 'how to kill', 'hot chick', 'hot carl', 'hooker', 'honkey', 'homoerotic', 
'hentai', 'hardcore', 'hard core', 'handjob', 'hand job', 'guro', 'g-spot', 'group sex', 'grope', 'goregasm', 
'goo girl', 'goodpoop', 'golden shower', 'gokkun', 'god damn', 'goatse', 'goatcx', 'girls gone wild', 'girl on top', 'girl on', 
'giant cock', 'genitals', 'gay sex', 'gang bang', 'futanari', 'fudgepacker', 'fudge packer', 'fucktards', 'fucking', 'fuckin', 
'fuck buttons', 'fuck', 'frotting', 'footjob', 'foot fetish', 'fisting', 'fingering', 'fingerbang', 'figging', 'femdom', 
'female squirting', 'feltch', 'fellatio', 'felch', 'fecal', 'faggot', 'eunuch', 'escort', 'erotism', 'erotic', 
'ejaculation', 'ecchi', 'eat my ass', 'dvda', 'dry hump', 'dp action', 'double penetration', 'double dong', 'donkey punch', 'dommes', 
'dominatrix', 'domination', 'dolcett', 'dog style', 'doggystyle', 'doggy style', 'doggiestyle', 'doggie style', 'dirty sanchez', 'dirty pillows', 
'dingleberries', 'dingleberry', 'dildo', 'dick', 'dendrophilia', 'deepthroat', 'deep throat', 'daterape', 'date rape', 'darkie', 
'cunt', 'cunnilingus', 'cumming', 'cum', 'creampie', 'coons', 'coon', 'cornhole', 'coprophilia', 'coprolagnia', 
'cocks', 'cock', 'clusterfuck', 'clover clamps', 'clitoris', 'clit', 'cleveland steamer', 'circlejerk', 'chocolate rosebuds', 'carpetmuncher', 
'carpet muncher', 'camwhore', 'camslut', 'camgirl', 'camel toe', 'butthole', 'buttcheeks', 'butt', 'busty', 'bunghole', 
'bung hole', 'bullshit', 'bullet vibe', 'bulldyke', 'bukkake', 'brunette action', 'brown showers', 'booty call', 'boobs', 'boob', 
'boner', 'bondage', 'bollocks', 'blumpkin', 'blue waffle', 'blow your load', 'blow job', 'blowjob', 'blonde on blonde action', 'blonde action', 
'black cock', 'bitches', 'bitch', 'birdlock', 'bimbos', 'big tits', 'big knockers', 'big breasts', 'big black', 'bestiality', 
'beaver lips', 'beaver cleaver', 'beaners', 'beaner', 'bdsm', 'bbw', 'bastinado', 'bastardo', 'bastard', 'barenaked', 
'barely legal', 'bareback', 'bangbros', 'ball sucking', 'ball sack', 'ball licking', 'ball kicking', 'ball gravy', 'ball gag', 'baby juice', 
'baby batter', 'babeland', 'autoerotic', 'auto erotic', 'assmunch', 'asshole', 'ass', 'arsehole', 'apeshit', 'anus', 
'anilingus', 'anal', 'alaskan pipeline', 'alabama hot pocket', 'acrotomophilia', '2 girls 1 cup', '2g1c'  ];
